// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdrfnvdhygasmxxvxvtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcmZudmRoeWdhc214eHZ4dnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzA3NTQsImV4cCI6MjA2NjMwNjc1NH0.ny5RkL_XfKXO7c2RPpPGtxV9TDmzJsXVFAsXnQeaBqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);